
export const SET_USER = "SET_USER";
export const SET_SEQUENCE_ARR = "SET_SEQUENCE_ARR";
export const SET_USER_SEQUENCE_ARR = "SET_USER_SEQUENCE_ARR";
export const SET_CURRENT_PRESSED = "SET_CURRENT_PRESSED";


export const SET_CURRENT_SCORE= "SET_CURRENT_SCORE";
export const SET_IS_GAME_OVER= "SET_IS_GAME_OVER";
export const SET_IS_PLAYING= "SET_IS_PLAYING";
export const SET_LEADER_BORD= "SET_LEADER_BORD";



